=== AlexisThach/CabinetInfirmier/src/data/xsd/cabinet.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/medical"
           xmlns:ci="http://www.univ-grenoble-alpes.fr/l3miage/medical"
           elementFormDefault="qualified">
    
    <!-- Élément racine qui est le cabinet avec le type "Cabinet"   -->
    <xs:element name="cabinet" type="ci:Cabinet"/>
    
    <!-- Type complexe pour le cabinet -->
    <xs:complexType name="Cabinet">
        <xs:sequence>
            <xs:element name="nom" type="xs:string" minOccurs="1"></xs:element>
            <xs:element name="adresse" type="ci:Adresse" minOccurs="1"></xs:element>
            <xs:element name="infirmiers" type="ci:Infirmiers" minOccurs="1"></xs:element>
            <xs:element name="patients" type="ci:Patients" minOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Type complexe pour l'adresse -->
    <xs:complexType name="Adresse">
        <xs:sequence>
            <xs:element name="etage" type="xs:string" minOccurs="0"/>
            <xs:element name="numéro" type="xs:string" minOccurs="0"/>
            <xs:element name="rue" type="xs:string" minOccurs="1"/>
            <xs:element name="codePostal" type="ci:CodePostal" minOccurs="1"/>
            <xs:element name="ville" type="xs:string" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Définition du type complexe "Infirmiers" -->
    <xs:complexType name="Infirmiers">
        <xs:sequence>
            <!-- Élément représentant la liste des infirmiers -->
            <xs:element name="infirmier" type="ci:Infirmier" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <!-- Définition du type complexe "Infirmier" -->
    <xs:complexType name="Infirmier">
        <xs:sequence>
            <!-- Éléments représentant les attributs de l'infirmier -->
            <xs:element name="nom" type="xs:string" minOccurs="1"/>
            <xs:element name="prénom" type="xs:string" minOccurs="1"/>
            <xs:element name="photo" type="ci:Photo" minOccurs="1"/>
        </xs:sequence>
        <!-- Attribut "id" pour l'identifiant de l'infirmier -->
        <xs:attribute name="id" type="ci:Id" use="required"/>
    </xs:complexType>

    <!-- Définition du type complexe "Patients" -->
    <xs:complexType name="Patients">
        <xs:sequence>
            <!-- Élément représentant la liste des patients -->
            <xs:element name="patient" type="ci:Patient" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <!-- Définition du type complexe "Patient" -->
    <xs:complexType name="Patient">
        <xs:sequence>
            <!-- Éléments représentant les attributs du patient -->
            <xs:element name="nom" type="ci:NomPatient" minOccurs="1"/>
            <xs:element name="prénom" type="ci:NomPatient" minOccurs="1"/>
            <xs:element name="sexe" type="ci:Sexe" minOccurs="1"/>
            <xs:element name="naissance" type="xs:date" minOccurs="1"/>
            <xs:element name="numéroSS" type="ci:NIR" minOccurs="1"/>
            <xs:element name="adresse" type="ci:Adresse" minOccurs="1"/>
            <xs:element name="visite" type="ci:Visite" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Type complexe pour les visites -->
    <xs:complexType name="Visite">
        <xs:sequence>
            <!-- Élément représentant la liste des actes de la visite -->
            <xs:element name="acte" type="ci:Acte" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <!-- Attributs "date" pour la date de la visite et "intervenant" en option -->
        <xs:attribute name="date" type="xs:date" use="required"/>
        <xs:attribute name="intervenant" type="xs:int" use="optional"/>
    </xs:complexType>
    
    <!-- Type complexe pour les actes -->
    <xs:complexType name="Acte">
        <xs:attribute name="id" type="xs:int" use="optional"/>
    </xs:complexType>
    
    <!-- Le type Id restrictif qui doit contenir 3 caractères -->
    <xs:simpleType name="Id">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{3}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Type NomPatient restrictif qui doit contenir que des lettres, peut avoir des accents, caractères spéciaux 
         tels que le tiret, apostrophe et aussi des espaces -->
    <xs:simpleType name="NomPatient">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-zÀ-ÿ .'-]+"/> 
            <xs:minLength value="1"/>  
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Type CodePostal est une restriction sur les codes postaux français -->
    <xs:simpleType name="CodePostal">
        <xs:restriction base="xs:string">  
            <!-- deux alternatives séparés par le pipe "|": 
                 1 - départements 01 à 09 
                 2 - départements 10 à 98 -->
            <xs:pattern value="0[1-9]\d{3}|[1-9]\d{4}"/>      
        </xs:restriction>
    </xs:simpleType>

    <!-- Le type simple Photo -->
    <xs:simpleType name="Photo">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*\.(png|jpg)"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Le type simple NIR (numéro de sécurité sociale) -->
    <xs:simpleType name="NIR">
        <xs:restriction base="xs:string">
            <xs:pattern value="[12]\d{2}(0[1-9]|1[0-2])(0[1-9]|[1-9]\d|2A|2B|99)\d{3}\d{3}\d{2}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Le type simple Sexe avec deux valeurs "M" et "F" -->
    <xs:simpleType name="Sexe">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="F"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== AlexisThach/CabinetInfirmier/src/data/xml/infirmiers.xml
<?xml version="1.0" encoding="UTF-8"?>
<infirmiers
        xmlns="http://www.univ-grenoble-alpes.fr/l3miage/medical"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/medical ../xsd/cabinet.xsd">
   
    <infirmier id="001">
        <nom>Fréchie</nom>
        <prénom>Sarah</prénom>
        <photo>frechie.png</photo>
    </infirmier>
    <infirmier id="002">
        <nom>Stické</nom>
        <prénom>Sophie</prénom>
        <photo>sophie.png</photo>
    </infirmier>
    <infirmier id="003">
        <nom>Ochon</nom>
        <prénom>Paul</prénom>
        <photo>paul.png</photo>
    </infirmier>
</infirmiers>

=== AlexisThach/CabinetInfirmier/src/data/xml/cabinet.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xslt/cabinet.xslt"?>
<cabinet xmlns="http://www.univ-grenoble-alpes.fr/l3miage/medical" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/medical ../xsd/cabinet.xsd">
  <!--Racine du document cabinet.xml-->
  <nom>Soins à Grenoble</nom>
  <adresse>
    <numéro>60</numéro>
    <rue>rue de la Chimie</rue>
    <codePostal>38041</codePostal>
    <ville>Grenoble</ville>
  </adresse>
  <!--Liste des infirmiers-->
  <infirmiers>
    <infirmier id="001">
      <nom>Fréchie</nom>
      <prénom>Sarah</prénom>
      <photo>sarah.png</photo>
    </infirmier>
    <infirmier id="002">
      <nom>Stické</nom>
      <prénom>Sophie</prénom>
      <photo>sophie.png</photo>
    </infirmier>
    <infirmier id="003">
      <nom>Ochon</nom>
      <prénom>Paul</prénom>
      <photo>paul.png</photo>
    </infirmier>
  </infirmiers>
  <!--Liste des patients-->
  <patients>
    <patient>
      <nom>Alécole</nom>
      <prénom>Yvon</prénom>
      <sexe>M</sexe>
      <naissance>1998-08-02</naissance>
      <numéroSS>198082205545852</numéroSS>
      <adresse>
        <étage>6</étage>
        <numéro>50</numéro>
        <rue>avenue Félix Viallet</rue>
        <codePostal>38031</codePostal>
        <ville>Grenoble</ville>
      </adresse>
      <visite date="2015-12-08" intervenant="001">
        <acte id="109" />
      </visite>
    </patient>
    <!-- Elvire Orouge est née le 08 mars 82 en France, à Lyon (n° 23 dans le rhône), il s’agissait de la 52e
         naissance dans cette ville. -->
    <patient>
      <nom>Orouge</nom>
      <prénom>Elvire</prénom>
      <sexe>F</sexe>
      <naissance>1982-03-08</naissance>
      <numéroSS>282036902305218</numéroSS>
      <adresse>
        <rue>Rond-Point de la Croix de Vie</rue>
        <codePostal>38700</codePostal>
        <ville>La Tronche</ville>
      </adresse>
      <visite date="2015-12-08">
        <acte id="300" />
      </visite>
    </patient>
    <!-- Oscare Pien est née le 25 mars 75 en France, à Chambéry (n° 65 dans la Savoie). 
         Il s’agissait de la 692e naissance. -->
    <patient>
      <nom>Pien</nom>
      <prénom>Oscare</prénom>
      <sexe>F</sexe>
      <naissance>1975-03-25</naissance>
      <numéroSS>275037306569202</numéroSS>
      <adresse>
        <rue>rue Casimir Brenier</rue>
        <codePostal>38000</codePostal>
        <ville>Grenoble</ville>
      </adresse>
      <visite date="2015-12-08" intervenant="001">
        <acte id="101" />
        <acte id="104" />
      </visite>
    </patient>
    <!--Xavier Kapoëtla est un petit garçon de 4 ans né le 02 août 2011 en France, à Bordeaux (n° 63 dans la Gironde).
        Il s'agit de la 35e naissance-->
    <patient>
      <nom>Kapoëtla</nom>
      <prénom>Xavier</prénom>
      <sexe>M</sexe>
      <naissance>2011-08-02</naissance>
      <numéroSS>111083306303521</numéroSS>
      <adresse>
        <numéro>25</numéro>
        <rue>rue des Martyrs</rue>
        <codePostal>38042</codePostal>
        <ville>Grenoble</ville>
      </adresse>
      <visite date="2015-12-08">
        <acte id="111" />
      </visite>
    </patient>
</patients>
</cabinet>
